---
title: "Merger Arbitrage"
author: "LB"
date: "10/7/2020"
output: html_document
---

```{r, setup, include=FALSE}
knitr::opts_chunk$set(
  message = FALSE, 
  warning = FALSE, 
  tidy=FALSE,     # display code as typed
  size="small")   # slightly smaller font for code
options(digits = 3)

# default figure size
knitr::opts_chunk$set(
  fig.width=6.75, 
  fig.height=6.75,
  fig.align = "center"
)
```


```{r load-libraries, include=FALSE}
library(tidyverse)  # Load ggplot2, dplyr, and all the other tidyverse packages
library(mosaic)
library(ggthemes)
library(lubridate)
library(here)
library(skimr)
library(janitor)
library(httr)
library(readxl)
library(vroom)
library(data.table)
library(infer)
library(ggridges)
library(viridis)
library(tidyquant)
library(rvest)    # scrape websites
library(purrr)  
library(lubridate) #to handle dates
library(ggrepel) # to avoid loverlapping legends
```



```{r, get tickers}

# we need a vector of strings with just the 30 tickers + SPY
stocks <- 
  data.frame(acquirer = c("ADS","AAPL"),
             target = c("NKE", "GOOGL"),
             acquirer_stocks = c(-1, -2),
             target_stocks = c(5, 6),
             announce_date =c(
               "2011-10-06",
               "2011-09-07"),
             close_date =c(
               "2014-10-03",
               "2012-09-05"))

```

```{r get_price_data, message=FALSE, warning=FALSE, cache=TRUE}
# Notice the cache=TRUE argument in the chunk options. Because getting data is time consuming, # cache=TRUE means that once it downloads data, the chunk will not run again next time you knit your Rmd

stock_data_acquirer <- stocks %>% 
  select(acquirer) %>% 
  tq_get(get  = "stock.prices",
         from = "2009-01-01",
         to   = "2020-08-31") %>%
  group_by(acquirer) %>% 
  select(acquirer, date, close) %>% 
  mutate(close_acquirer = sprintf("%.2f",close))

stock_data_acquirer_target <- left_join(stock_data_acquirer,stocks , by=c("acquirer"))


stock_data_returns_acquirer <- stocks %>% 
  select(acquirer) %>% 
  tq_get(get  = "stock.prices",
         from = "2009-01-01",
         to   = "2020-08-31") %>%
  group_by(acquirer) %>% 
  select(acquirer, date, close) %>% 
  group_by(acquirer) %>%
    tq_transmute(select     = close, 
                 mutate_fun = periodReturn, 
                 period     = "daily", 
                 col_rename = "R_d_acquirer")

df_acquirer <- left_join(stock_data_acquirer_target,stock_data_returns_acquirer , by=c("acquirer","date"))

glimpse(df_acquirer)

stock_data_target <- stocks %>% 
  select(target) %>% 
  tq_get(get  = "stock.prices",
         from = "2009-01-01",
         to   = "2020-08-31") %>%
  group_by(target) %>% 
  select(target, date, close) %>% 
  mutate(close_target = sprintf("%.2f",close))

stock_data_returns_target <- stocks %>% 
  select(target) %>% 
  tq_get(get  = "stock.prices",
         from = "2009-01-01",
         to   = "2020-08-31") %>%
  group_by(target) %>% 
  select(target, date, close) %>% 
  group_by(target) %>%
    tq_transmute(select     = close, 
                 mutate_fun = periodReturn, 
                 period     = "daily", 
                 col_rename = "R_d_target")

df_target <- left_join(stock_data_target,stock_data_returns_target , by=c("target","date"))

df_returns <- left_join(df_acquirer,df_target , by=c("date","target")) 

df_returns <- df_returns %>% 
    mutate(announce_date = as.Date(announce_date,"%Y-%m-%d"),
           close_date = as.Date(close_date,"%Y-%m-%d"),
           standard_date = date - announce_date) %>% 
  group_by(acquirer) %>% 
  filter(standard_date >= -2,
         date <= close_date)



df_returns <- df_returns[,c("date",
                            "standard_date",
                            "announce_date",
                            "close_date",
                            "acquirer",
                            "target",
                            "close_acquirer",
                            "close_target",
                            "R_d_acquirer",
                            "R_d_target")]

df_returns_portfolio <- left_join(df_returns, stocks , by=c("acquirer","target"))  %>% 
  select(-announce_date.y, -close_date.y) %>% 
  mutate(close_acquirer = parse_number(close_acquirer),
         close_target = parse_number(close_target),
         portfolio_value = (acquirer_stocks * close_acquirer) + (target_stocks * close_target)) %>% 
  group_by(acquirer) %>% 
  mutate(R_d_portfolio =  portfolio_value/lag(portfolio_value) - 1)

# reformat geometric formula to exponential formula https://en.wikipedia.org/wiki/Geometric_mean#:~:text=2%2C%20that%20is%2C-,.,a%20financial%20investment%20over%20time.
gm_mean = function(x, na.rm=TRUE){
  exp(sum(log(1+x)) / length(x)) -1}

# df_summary <- df_returns %>% 
#   group_by(acquirer) %>% 
#   summarise(total_cagr_acquirer = gm_mean(R_d_acquirer),
#             total_cagr_target = gm_mean(R_d_target))


df_standard_daily_returns <- df_returns_portfolio %>% 
  group_by(standard_date) %>% 
  summarise(return_acquirer = gm_mean(R_d_acquirer),
            return_target = gm_mean(R_d_target),
            return_portfolio = gm_mean(R_d_portfolio))

glimpse(df_returns) # examine the structure of the resulting data frame

# To Dos
## Get standard dates into proper series. - Dung
## Add portfolio set-up and portfolio close price - Leif
## calculate portfolio daily returns  -> mutate( ret = close_price/lag(close_price) - 1) - Leif
## calculate daily returns across deals with gm_function - Leif
## plot results - Dung
## measure performance. Regression with Market index -> calculate Alpha and Beta - Dung



```

```{r plot returns}

df_returns %>% 
  ggplot() +
  geom_line(aes(x = standard_date, y = close_acquirer, group = acquirer, colour = acquirer))

```




```{r standardised format}
datalist = list() 

for (i in test) {
  df <- data.frame(c1 = c(1,2),
                   c2 = c(3,4)) %>% 
    mutate(comp = i)
  

  merge <- rbind(merge,df)
  }


glimpse(merge)
```


